### ISSUE TITLE
Documentation Improvement: Include OnSuccess() Example

### ISSUE THREAD

**Issue by homestar9** [horprogs/Just-validate#113]
I've seen a few StackOverflow posts and ran into an issue myself when trying to submit a form after validation.  I assumed that the form would submit automatically if validation was successful.  However, I eventually learned it does not.  

The documentation could be improved by including the following note that the `onSuccess()` method needs to be added to the validator.

Example:
```
validator
    .addField( '#emailAddress', [
        { rule: 'required' },
        { rule: 'email' }
    ] )
    // important! This is required for normal form submission
    .onSuccess( ( event ) => {
        event.currentTarget.submit();
    } );
```

I would include the note along with some sample code in the following places:
https://just-validate.dev/docs/methods/onSuccess
https://just-validate.dev/docs/intro
https://just-validate.dev/examples

**Comment by kokoal** [comment]
I think this can be the legacy way of submitting a form before Safari 16.

The new way of submitting a form is with `requestSubmit`, see https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit.

Using `requestSubmit` avoid massive problems when using it in some framework or CMS (like Drupal) because there is a submitter element and the system can detect which input or button is responsible for submitting the form and process it correctly.

**Comment by silent-e** [comment]
`requestSubmit()` didn't work for me.  I had to use `submit()`.  FYI.

+1 from me on this issue.

**Comment by evelynDickinson** [comment]
I came here to say this. Please update the docs!

**Comment by PiemP** [comment]
Has anyone found a good way to submit a valid form with the value of the button press to create submit event?

**Comment by horprogs** [comment]
Thanks, guys. Finally adjusted the docs and added a new setting `submitFormAutomatically` that submits the form automatically if the validation is successful.
