### ISSUE TITLE
JustValidate call parameter / errors messages repetition.

### ISSUE THREAD

**Issue by Outsider1985** [horprogs/Just-validate#57]
**Describe the bug**
In order to create an object "validation" with JustValidate I must write ("#" + form.id) as parameter. In order to destroy a failed validation error messages I must use a fix with an array "invalidElements" or errors warnings repeat by using button.addEventListener("click", () => {...});

**Expected behavior**
form.id should be enough as parameter. A method is requiered for destroying errors messages in order to avoid repeating themselves without exceptions. validation.isValid()==false as conditional doesn't work as I expected. Maybe it's just my incompetence. If it is the case, I apologise :)

Javier Ulises
![validator_function](https://user-images.githubusercontent.com/99191119/162476230-f48f31f2-803f-414b-a878-04e0cf79cf76.jpg)
![form_function](https://user-images.githubusercontent.com/99191119/162476237-8de1d90b-b4ba-4c7b-a661-7cf95d3fce7b.jpg)

**Comment by horprogs** [comment]
Hey! The `JustValidate` constructor could take either a string selector or an element, so you don't need to do `'#' + form.id`, instead of this you could just put `JustValidate(form)`.

Instead of `validation.isValid()==false` please try `validation.isValid === false`, because `isValid` is a property, not a method.

I'm not sure I understood the idea to destroy the instance if there are invalid messages... I see you use the button click listener, but the library already listening for the form submitting, so you don't need to handle the button click.
