### ISSUE TITLE
minLength rule validates successfully on empty fields

### ISSUE THREAD

**Issue by SergeyXXI** [horprogs/Just-validate#59]
Why does your minLength rule validate successfully on empty fields? You made it on purpose? It's not obvious and ambiguous, don't you think so? It means, we need extra specify "required" rule for empty fields, because "minLength" rule works like empty value >= minLength value. This is strange, and I hope you fix it.

**Comment by horprogs** [comment]
Hello, yes this was done deliberately, because I believe the rules should be atomic and have the single responsibility. Also there is a case when you don't want to validate the field if there is no value (https://github.com/horprogs/Just-validate/issues/31), that's why it's better to have 2 different types: for validation length and required values separately.
