### ISSUE TITLE
Submit form

### ISSUE THREAD

**Issue by iteidrm** [horprogs/Just-validate#72]
Please excuse me from opening an issue about this perhaps naiv question.

Am i correct in assuming that I have to submit the form "manually" after validation (onSuccess?) when using this library?

I couldn't find any reference to that in the documentation or in the example code.

**Comment by horprogs** [comment]
Hi, sorry for the late response. It works in this way:

1. User fills the fields
2. User clicks the submit button (it means you should have a submit button in your form)
3. The library listens the submit event and perform the validation. If it succeed `onSuccess` callback will be called and you could run any code you want there (like sending api requests etc)

So you don't need to submit form manually. User does this.

**Comment by jbmcfarlin31** [comment]
@horprogs new user here with JS and this particular library.. but I am also facing the same issue as the OP.

I implemented it into my web page when my button is clicked to submit my form, the validation appears to work as I get notices for fields that need to be filled out or that don't match my constraints, however, my submit button then appears to be locked or frozen. It will not finish submitting my form as a POST.

I have added the following in the `onSuccess` method:
```
.onSuccess((event) => {
                console.log("validation passed", event);
                event.preventDefault();
                window.showNotification();
                event.target.submit();
            });
```
But that still doesn't seem to actually do the POST of my form.

**Comment by iteidrm** [comment]
Hi, thank you very much for your response.

Ah, at the time of writing / testing, someone else has also commented.

I've tested a few things including the example from the documentation: https://jsfiddle.net/dkt17m8e

As @jbmcfarlin31 mentioned, even when I changed the type of the button to "submit", the form would not work.

Im had to go with ...
```
.onSuccess((event) => {
    validation.form.submit();
});
```
... to make it work.

Thanks for your time.

**Comment by jbmcfarlin31** [comment]
@horprogs I tried both your solution and @iteidrm with no luck.. here is my code: https://codesandbox.io/s/just-validate-template-forked-544frv?file=/index.html

**Comment by horprogs** [comment]
I'm not sure what's wrong with Codesandbox, but if you put js code into a separate file it works fine. When you fill all fields properly the POST request is made and Codesandbox shows 405 error (because POST requests are not allowed there).

Check it out: https://codesandbox.io/s/just-validate-template-forked-d8pm6o?file=/src/index.js

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/14051960/174038782-3a1e8cb7-cbb1-4f26-afd8-adbd40e61e40.png">

**Comment by jbmcfarlin31** [comment]
@horprogs so I moved my validation code into it's own file and imported it onto my web page that way. Behaves the same as before.

I get a POST notification and see it happening in dev tools, but it isn't doing a POST to the correct URL. On my submit button, I have a `formaction="/auth/url"` and my default form action is `action="#"`. It appears to be posting to the same url (in this case, `/sign-up`) instead of `/auth/url`.

Does the validator take into consideration the `formaction` attribute? I am also using `validation.form.submit()` in the `onSuccess` call.

**Comment by horprogs** [comment]
Actually, when you trigger the form manually, `formaction` for the submit button will not work. Could you use the form `action` attribute to specify the POST url? it should work

**Comment by jbmcfarlin31** [comment]
@horprogs in this case, I am able to set that attribute at the form `action` level. Thankfully my other forms don't require validation, so I think I can get by with the `formaction` attribute on the buttons. I just tested your suggestion and my form is working now with the validation.

Not sure if that is something that can be looked at.. but might worth trying to investigate to see if you can add that. Thanks for the help!

**Comment by horprogs** [comment]
Glad that it helped! Actually there is nothing to do here, unfortunately, because this is how the JS validation works: you have to prevent submitting and trigger it again (using `action`)
